version: '3'

services:
  s_ddd_server:
    container_name: c_ddd_server
    build:
      context: .
      dockerfile: docker/nginx/dockerfile
    ports:
      - '8084:80'
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/vhost/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
    depends_on:
      - s_ddd_php
      - s_ddd_mysql
    networks:
      - dev

  s_ddd_mysql:
      container_name: c_ddd_mysql
      image: mysql:8
      volumes:
          - ./docker/data/db:/var/lib/mysql:rw
          - ./docker/var/sql:/sql
          - ./docker/mysql/conf:/etc/mysql/conf.d
      environment:
          MYSQL_ROOT_PASSWORD: okLYM456ui
          MYSQL_DATABASE: db_sf6_redis
          MYSQL_USER: sf6_redis
          MYSQL_PASSWORD: sf6_redis
      ports:
          - 42335:3306
      networks:
        - dev

  s_ddd_php:
      container_name: c_ddd_php
      build:
          dockerfile: Dockerfile
      depends_on:
          - s_ddd_mysql
      links:
          - s_ddd_mysql
      volumes:
          - .:/var/www/html:rw,cached
      networks:
        - dev

networks:
  dev: